AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template will create S3 Bucket, Loging Bucket and Bucket Policy. 
  It will include Website Host Configurations and 
  also enable versioning configuations. It gives a output as URL of website.

Resources:
  EnesS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: enes-s3-cfn-7145
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: testing-logs
      VersioningConfiguration:
        Status: Enabled

  LoggingBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: LogDeliveryWrite
      BucketName: enes-s3-log-cfn-7145
    
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref EnesS3Bucket
                - /*
      Bucket: !Ref EnesS3Bucket

Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - EnesS3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - EnesS3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content